### PR TITLE
added parse_schedule function and enhancements to the extract_course_…

### PR DESCRIPTION
**Pull request by ghost**
…details function for improved error handling and schedule parsing.

### CODE REVIEW

**Comment by raissonsouto** [comment]
Hey @PedramHaeri, I'm very happy in receiving your PR. The concept behind the issue you ask to be signed involves breaking down `scrape_data()` into smaller functions, is well executed with the creation of `parse_schedule()`. However, it appears that there are some missing functions, such as a function to get the professor (or professors) name, obtaining the class name, retrieving the vancancies and fetching class id.

Also, remove the comment lines (if the comment is really needed, it should be in the docstring) and the comment function as well.

**Comment by ghost** [comment]
Thanks for your feedback. I just added the necessary functions based on the original one and cleaned up the comments. Please let me know if you have any more questions

**Comment by raissonsouto** [comment]
I checked out the new code version and I'm glad you made some great improvements based on my feedback. But here's the thing: even though you created those suggested functions, you haven't used them anywhere in the code. So, why aren't you calling them?

**Comment by ghost** [comment]
Oops silly me. I forgot to add the updated function. Give me a minute and I'll get it updated

**Comment by raissonsouto** [comment]
thanks for your contribution :rocket:

**Pull request merged**
